application: mrtaskman
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- deferred: on

handlers:

# Tasks.
- url: /tasks/[0-9]+
  script: handlers.tasks.app
- url: /tasks/assign
  script: handlers.tasks.app
- url: /tasks/schedule
  script: handlers.tasks.app
- url: /tasks/timeout
  script: models.tasks.app

