application: mrtaskman
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on
- deferred: on

handlers:

# Tasks.
- url: /tasks/[0-9]+
  script: handlers.tasks.app
- url: /tasks/assign
  script: handlers.tasks.app
- url: /tasks/schedule
  script: handlers.tasks.app
- url: /tasks/timeout
  script: models.tasks.app

# Packages.
- url: /packages/create
  script: handlers.packages.app
- url: /packages/[a-zA-Z]+\.[0-9\.]+
  script: handlers.packages.app
- url: /packagefiles/.+
  script: handlers/packagefiles.py

