application: mrtaskman
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- deferred: on

handlers:

- url: /tasks/schedule
  script: handlers.tasks_handlers.app
- url: /tasks/([0-9]+)
  script: handlers.tasks_handlers.app
